namespace FootballSimulation.Models;

public enum PlayerTrait
{
    FinesseShot,
    PowerHeader,
    Flair,
    SpeedDribbler,
    Playmaker,
    LongPasser,
    LongShotTaker,
    OutsideFootShot,
    Leadership,
    TeamPlayer,
    DivesIntoTackles,
    Interceptor,
    OneOnOnes,
    RushesOutOfGoal,
    Puncher,
    LongThrower,
    TriesToBeatOffsideTrap,
    InjuryProne,
    PressResistant,
    ClinicalFinisher,
    DeadBallSpecialist,
    Engine,
    BoxToBox,
    AerialThreat,
    Rapid,
    TechnicalDribbler,
    PenaltySpecialist,
    BigMatchPlayer,
    Strong,
    Acrobatics,
    FirstTouch,
    Poacher,
    TargetForward,
    RelentlessPresser,
    BallWinner,
    RecoveryPace,
    Composed,
    CrossingSpecialist,
    ShotStopper,
    CrossClaimer,

    PlayMaker = Playmaker,
    OneOnOnesGK = OneOnOnes,
    LongThrowerGK = LongThrower,
    PuncherGK = Puncher,
    SolidPlayer = Engine,
    SecondWind = Engine,
    PushesUpForCornersGK = RushesOutOfGoal,
    AggressiveTackler = DivesIntoTackles,
    PaceMerchant = Rapid,
    SetPieceSpecialist = DeadBallSpecialist,
    EarlyCrosser = CrossingSpecialist
}
