namespace FootballSimulation.Models;

public enum PlayerTrait
{
    FinesseShot,
    PowerHeader,
    Flair,
    SpeedDribbler,
    Playmaker,
    LongPasser,
    LongShotTaker,
    EarlyCrosser,
    OutsideFootShot,
    Leadership,
    TeamPlayer,
    DivesIntoTackles,
    Interceptor,
    OneOnOnes,
    RushesOutOfGoal,
    Puncher,
    LongThrower,
    TriesToBeatOffsideTrap,
    InjuryProne,
    PressResistant,
    ClinicalFinisher,
    DeadBallSpecialist,
    Engine,
    BoxToBox,
    AerialThreat,
    Rapid,
    TechnicalDribbler,

    PlayMaker = Playmaker,
    OneOnOnesGK = OneOnOnes,
    LongThrowerGK = LongThrower,
    PuncherGK = Puncher,
    SolidPlayer = Engine,
    SecondWind = Engine,
    PushesUpForCornersGK = RushesOutOfGoal,
    AggressiveTackler = DivesIntoTackles,
    PaceMerchant = Rapid,
    SetPieceSpecialist = DeadBallSpecialist,
    BigMatchPlayer = Leadership
}
